### ISSUE TITLE
Code of docs about create pptx result without any content

### ISSUE THREAD

**Issue by jingliancui** [OfficeDev/open-xml-docs#53] opened 2020-09-14 02:10 UTC
Refer to https://github.com/OfficeDev/Open-XML-SDK/issues/801

- [ √ ] Question on library usage

https://docs.microsoft.com/en-us/office/open-xml/how-to-create-a-presentation-document-by-providing-a-file-name

sample code same to docs
[ConsoleApp.zip](https://github.com/OfficeDev/Open-XML-SDK/files/5180913/ConsoleApp.zip)

result:
![result](https://user-images.githubusercontent.com/16309962/92345502-21efa600-f0fc-11ea-9ff4-fb7c98f3cbd4.jpg)

**Comment by jingliancui** [comment] 2020-09-14 02:11
Don't know it's the library issue or if the docs not complete in msdocs.

**Comment by mikeebowen** [comment] 2024-12-31 22:13
closing this as by design.

**Closed by mikeebowen** 2024-12-31 22:13 UTC
